(function() {
  var subjects = [
    { key: 'matte', name: 'Matte' },
    { key: 'fysik', name: 'Fysik' },
    { key: 'kemi', name: 'Kemi' },
    { key: 'biologi', name: 'Biologi' },
    { key: 'geografi', name: 'Geografi' },
    { key: 'historia', name: 'Historia' },
  ];

  var words = [ { key: '+', name: '+', subject: 'matte', youtube: 'i7glsemqTGg' },
  { key: '-', name: '-', subject: 'matte', youtube: 'CS6eBTAS9ls' },
  { key: '=', name: '=', subject: 'matte', youtube: 'T1w5d5tRy0E' },
  { key: 'addition',
    name: 'addition',
    subject: 'matte',
    youtube: 'Sjn5kpLPv1E' },
  { key: 'addition',
    name: 'addition',
    subject: 'matte',
    youtube: 'DI8F2aSYPn4' },
  { key: 'addition_term+term=summa',
    name: 'addition term+term=summa',
    subject: 'matte',
    youtube: '9SPFe2auUlc' },
  { key: 'algebra',
    name: 'algebra',
    subject: 'matte',
    youtube: '5DhvGA9K4og' },
  { key: 'alla_-_många_-_några_-_få',
    name: 'alla - många - några - få',
    subject: 'matte',
    youtube: 'jsyYjs0-l-A' },
  { key: 'alla_-_många_-_några_-_få',
    name: 'alla - många - några - få',
    subject: 'matte',
    youtube: 'qBRSE8eQobE' },
  { key: 'andra_alt_1',
    name: 'andra alt 1',
    subject: 'matte',
    youtube: '0DhR_0yAYGg' },
  { key: 'andra_alt_2',
    name: 'andra alt 2',
    subject: 'matte',
    youtube: 'AGFv0FTo3Ys' },
  { key: 'antal',
    name: 'antal',
    subject: 'matte',
    youtube: '67E_EK4Ngeo' },
  { key: 'area',
    name: 'area',
    subject: 'matte',
    youtube: 't8wR4jZIsgI' },
  { key: 'avläsa',
    name: 'avläsa',
    subject: 'matte',
    youtube: 'KaCIsIsnTc0' },
  { key: 'avrunda',
    name: 'avrunda',
    subject: 'matte',
    youtube: '6qZpf2IzwsI' },
  { key: 'avrunda',
    name: 'avrunda',
    subject: 'matte',
    youtube: 'SBPdmPO_6yw' },
  { key: 'avrundning',
    name: 'avrundning',
    subject: 'matte',
    youtube: '_pRzYJcaISk' },
  { key: 'avstånd',
    name: 'avstånd',
    subject: 'matte',
    youtube: '7CvvHq5MU4Y' },
  { key: 'bakåt',
    name: 'bakåt',
    subject: 'matte',
    youtube: 'rjH0QtXhOkM' },
  { key: 'bakåt',
    name: 'bakåt',
    subject: 'matte',
    youtube: 'xqdDHucz0OA' },
  { key: 'bakom_alt_1',
    name: 'bakom alt 1',
    subject: 'matte',
    youtube: 'YD0-CKYh968' },
  { key: 'bakom_alt_2',
    name: 'bakom alt 2',
    subject: 'matte',
    youtube: 'CcAhLgH97Bg' },
  { key: 'bild',
    name: 'bild',
    subject: 'matte',
    youtube: 'eNUPQ1xKrYg' },
  { key: 'böjd',
    name: 'böjd',
    subject: 'matte',
    youtube: 'E_vVRAjCsnM' },
  { key: 'bråk',
    name: 'bråk',
    subject: 'matte',
    youtube: 'ST3Z0N7kUVI' },
  { key: 'bred',
    name: 'bred',
    subject: 'matte',
    youtube: 'Ae-PDzCy3jU' },
  { key: 'bredvid',
    name: 'bredvid',
    subject: 'matte',
    youtube: '0_WKTOU40zU' },
  { key: 'centiliter',
    name: 'centiliter',
    subject: 'matte',
    youtube: 'saSgWVBYCA0' },
  { key: 'cirkel',
    name: 'cirkel',
    subject: 'matte',
    youtube: 'Y6sq4LQYgGE' },
  { key: 'cirkeldiagram',
    name: 'cirkeldiagram',
    subject: 'matte',
    youtube: 'w_gSIsj_5bA' },
  { key: 'cm',
    name: 'cm',
    subject: 'matte',
    youtube: 'FZ8iCtNtgts' },
  { key: 'cylinder',
    name: 'cylinder',
    subject: 'matte',
    youtube: '0AmjGieVfNA' },
  { key: 'dålig',
    name: 'dålig',
    subject: 'matte',
    youtube: 'w79G5_SuOos' },
  { key: 'dålig_-_sämre_-_sämst',
    name: 'dålig - sämre - sämst',
    subject: 'matte',
    youtube: '2nKkofcrwGU' },
  { key: 'deciliter',
    name: 'deciliter',
    subject: 'matte',
    youtube: 'df6SLspgIAY' },
  { key: 'decimaltal',
    name: 'decimaltal',
    subject: 'matte',
    youtube: 'cGPOpaXPCcc' },
  { key: 'decimeter',
    name: 'decimeter',
    subject: 'matte',
    youtube: '39bf_iuhMMA' },
  { key: 'dela',
    name: 'dela',
    subject: 'matte',
    youtube: 'KqfPKt2RNvU' },
  { key: 'diagram',
    name: 'diagram',
    subject: 'matte',
    youtube: 'QEYPG47rrJM' },
  { key: 'differens',
    name: 'differens',
    subject: 'matte',
    youtube: 'TpGNCl4bqQc' },
  { key: 'digital',
    name: 'digital',
    subject: 'matte',
    youtube: '76XvlbOOP-s' },
  { key: 'division',
    name: 'division',
    subject: 'matte',
    youtube: 'pqC9uK09xVM' },
  { key: 'dubbelt',
    name: 'dubbelt',
    subject: 'matte',
    youtube: 'AU8fqqdWejs' },
  { key: 'dubbelt',
    name: 'dubbelt',
    subject: 'matte',
    youtube: 'CXLZTq8UxXg' },
  { key: 'dubblera',
    name: 'dubblera',
    subject: 'matte',
    youtube: 'x6IieiGpxP4' },
  { key: 'ekvation',
    name: 'ekvation',
    subject: 'matte',
    youtube: 'VKeOMSQGNtw' },
  { key: 'elfte',
    name: 'elfte',
    subject: 'matte',
    youtube: 't45zrpUQIgk' },
  { key: 'enhet',
    name: 'enhet',
    subject: 'matte',
    youtube: 'MEBydM4Brmg' },
  { key: 'ensiffrig',
    name: 'ensiffrig',
    subject: 'matte',
    youtube: 'CobMAESyyc4' },
  { key: 'ental',
    name: 'ental',
    subject: 'matte',
    youtube: 'XZTqBX_sPNY' },
  { key: 'faktor',
    name: 'faktor',
    subject: 'matte',
    youtube: 'I8cEVqqUTdQ' },
  { key: 'färre',
    name: 'färre',
    subject: 'matte',
    youtube: 'fcdpVGILvr0' },
  { key: 'färre_än',
    name: 'färre än',
    subject: 'matte',
    youtube: 'l-rQDxdlDSc' },
  { key: 'femhörning',
    name: 'femhörning',
    subject: 'matte',
    youtube: 'A3F_6lOPQS4' },
  { key: 'femte',
    name: 'femte',
    subject: 'matte',
    youtube: 'Bn85y3DiU4k' },
  { key: 'figur',
    name: 'figur',
    subject: 'matte',
    youtube: '9fA8Cm8AP1E' },
  { key: 'fjärde',
    name: 'fjärde',
    subject: 'matte',
    youtube: 'jQ-HGPyBJbM' },
  { key: 'fjärdedel',
    name: 'fjärdedel',
    subject: 'matte',
    youtube: 'QDRH3sSbIdE' },
  { key: 'fler',
    name: 'fler',
    subject: 'matte',
    youtube: 'Nbvs_Up-kaA' },
  { key: 'fler_-_flera_-_flest',
    name: 'fler - flera - flest',
    subject: 'matte',
    youtube: 'Us6C1O0ey0Q' },
  { key: 'fler_än',
    name: 'fler än',
    subject: 'matte',
    youtube: 'EiUS3HUe2Rk' },
  { key: 'flera',
    name: 'flera',
    subject: 'matte',
    youtube: 'XzztjwHqYuI' },
  { key: 'flest',
    name: 'flest',
    subject: 'matte',
    youtube: 'l5_szEzmMIE' },
  { key: 'flest',
    name: 'flest',
    subject: 'matte',
    youtube: '4d7F7dPqJqI' },
  { key: 'form',
    name: 'form',
    subject: 'matte',
    youtube: '5zX7X2EwLqQ' },
  { key: 'förminskning',
    name: 'förminskning',
    subject: 'matte',
    youtube: 'uTp-r6Eh35k' },
  { key: 'först',
    name: 'först',
    subject: 'matte',
    youtube: 'FTLd50ud7Eo' },
  { key: 'första',
    name: 'första',
    subject: 'matte',
    youtube: 'WTOOI_VFk_0' },
  { key: 'förstorning',
    name: 'förstorning',
    subject: 'matte',
    youtube: 'DMC4H1r-7LA' },
  { key: 'framåt',
    name: 'framåt',
    subject: 'matte',
    youtube: 'pLox8E_5wMg' },
  { key: 'framför',
    name: 'framför',
    subject: 'matte',
    youtube: 'otf2ViYFGeE' },
  { key: 'full_-_halvfull_-_tom',
    name: 'full - halvfull - tom',
    subject: 'matte',
    youtube: 'dmKZyU2XUtI' },
  { key: 'fyrhörning',
    name: 'fyrhörning',
    subject: 'matte',
    youtube: 'swIV6_7UGYY' },
  { key: 'g', name: 'g', subject: 'matte', youtube: 'fS2Ao9PgU-U' },
  { key: 'gånger',
    name: 'gånger',
    subject: 'matte',
    youtube: 'BmL_LJ9g6DU' },
  { key: 'geometri',
    name: 'geometri',
    subject: 'matte',
    youtube: 'twJL0LOvjVs' },
  { key: 'geometriska_kroppar',
    name: 'geometriska kroppar',
    subject: 'matte',
    youtube: '2rSvjUuf784' },
  { key: 'grader_celcius',
    name: 'grader celcius',
    subject: 'matte',
    youtube: '4SV5MUilCZI' },
  { key: 'grupp',
    name: 'grupp',
    subject: 'matte',
    youtube: 'zbaXMSfCK2Q' },
  { key: 'halv',
    name: 'halv',
    subject: 'matte',
    youtube: 'JGTo0DZoIeM' },
  { key: 'hälften_av_antal',
    name: 'hälften av antal',
    subject: 'matte',
    youtube: 'BDTqIdfnZKU' },
  { key: 'hälften_av_helhet',
    name: 'hälften av helhet',
    subject: 'matte',
    youtube: 'ZQ1QMRtw7T0' },
  { key: 'hektogram',
    name: 'hektogram',
    subject: 'matte',
    youtube: 'ZPQjtn_llvA' },
  { key: 'hög_låg',
    name: 'hög låg',
    subject: 'matte',
    youtube: 'GZee8kMTcUM' },
  { key: 'höger',
    name: 'höger',
    subject: 'matte',
    youtube: 'LAXIc47Vr5Q' },
  { key: 'hörn',
    name: 'hörn',
    subject: 'matte',
    youtube: 'A-5SKbVREME' },
  { key: 'hundratal',
    name: 'hundratal',
    subject: 'matte',
    youtube: 'MWqhU3KOLp8' },
  { key: 'huvudräkning',
    name: 'huvudräkning',
    subject: 'matte',
    youtube: 'P_HFz9_w398' },
  { key: 'inne_i',
    name: 'inne i',
    subject: 'matte',
    youtube: 'QmKcTpsC2lM' },
  { key: 'innehåll',
    name: 'innehåll',
    subject: 'matte',
    youtube: '--7No7y5i34' },
  { key: 'inte_lika_med',
    name: 'inte lika med',
    subject: 'matte',
    youtube: 'lOgUzyKy85E' },
  { key: 'jämför',
    name: 'jämför',
    subject: 'matte',
    youtube: 'KISkvL-jTDs' },
  { key: 'jämföra',
    name: 'jämföra',
    subject: 'matte',
    youtube: 'AbDnTq7ABI8' },
  { key: 'jämn',
    name: 'jämn',
    subject: 'matte',
    youtube: 'VRJz8Lx8ddU' },
  { key: 'jämnt',
    name: 'jämnt',
    subject: 'matte',
    youtube: 'u7GUYW5HdZA' },
  { key: 'kamrat',
    name: 'kamrat',
    subject: 'matte',
    youtube: 'mAPeFGUeaX0' },
  { key: 'kant',
    name: 'kant',
    subject: 'matte',
    youtube: 'dVzvEhH6_kg' },
  { key: 'kg',
    name: 'kg',
    subject: 'matte',
    youtube: 'KLWDopXUgMI' },
  { key: 'kilo',
    name: 'kilo',
    subject: 'matte',
    youtube: 'CHK5stWQknc' },
  { key: 'kilometer_alt_1',
    name: 'kilometer alt 1',
    subject: 'matte',
    youtube: 'zYuGqK9byHE' },
  { key: 'kilometer_alt_2',
    name: 'kilometer alt 2',
    subject: 'matte',
    youtube: 'IWll2DKg3tQ' },
  { key: 'klockan_alt_1',
    name: 'klockan alt 1',
    subject: 'matte',
    youtube: 'pILNqADYYBY' },
  { key: 'klockan_alt_2',
    name: 'klockan alt 2',
    subject: 'matte',
    youtube: 'f-mh76vqdNU' },
  { key: 'klockslag',
    name: 'klockslag',
    subject: 'matte',
    youtube: 'osRn_RtwySI' },
  { key: 'klot',
    name: 'klot',
    subject: 'matte',
    youtube: '61aZ-Oe9C4M' },
  { key: 'kombinera',
    name: 'kombinera',
    subject: 'matte',
    youtube: '63dWuxD3uaE' },
  { key: 'kon',
    name: 'kon',
    subject: 'matte',
    youtube: 'JTO1Nd3p5-I' },
  { key: 'koordinater',
    name: 'koordinater',
    subject: 'matte',
    youtube: 'wid50Ho-k1E' },
  { key: 'kort_alt_1',
    name: 'kort alt 1',
    subject: 'matte',
    youtube: 'rAbtjBazpTg' },
  { key: 'kort_alt_2',
    name: 'kort alt 2',
    subject: 'matte',
    youtube: '9-YPhSxHtXU' },
  { key: 'kort_kortare_kortast_alt_1',
    name: 'kort kortare kortast alt 1',
    subject: 'matte',
    youtube: 'iL4i9a6Ycts' },
  { key: 'kort_kortare_kortast_alt_2',
    name: 'kort kortare kortast alt 2',
    subject: 'matte',
    youtube: 'gyScMB8pS7c' },
  { key: 'kortare_alt_1',
    name: 'kortare alt 1',
    subject: 'matte',
    youtube: '8VMAC0GoCBU' },
  { key: 'kortare_alt_2',
    name: 'kortare alt 2',
    subject: 'matte',
    youtube: 'pVjPv-PrRNc' },
  { key: 'kortast_alt_1',
    name: 'kortast alt 1',
    subject: 'matte',
    youtube: 'wc0osOddQB0' },
  { key: 'kortast_alt_2',
    name: 'kortast alt 2',
    subject: 'matte',
    youtube: 'RZspKsyvXFY' },
  { key: 'kr_alt_1',
    name: 'kr alt 1',
    subject: 'matte',
    youtube: '8nHsfZ4__Mc' },
  { key: 'kr_alt_2',
    name: 'kr alt 2',
    subject: 'matte',
    youtube: 'HZFwsCta3Gc' },
  { key: 'kronor_alt_2',
    name: 'kronor alt 2',
    subject: 'matte',
    youtube: 'KiPNBFiXknk' },
  { key: 'kub',
    name: 'kub',
    subject: 'matte',
    youtube: 'SzeIO545JBs' },
  { key: 'kvadrat',
    name: 'kvadrat',
    subject: 'matte',
    youtube: 'Zkurv-QdToE' },
  { key: 'kvadratcentimeter',
    name: 'kvadratcentimeter',
    subject: 'matte',
    youtube: 'R1aq38HAi1Y' },
  { key: 'kvar',
    name: 'kvar',
    subject: 'matte',
    youtube: 'l9JNuVLf_ak' },
  { key: 'kvart',
    name: 'kvart',
    subject: 'matte',
    youtube: 'nWjqggwA508' },
  { key: 'kvart_i',
    name: 'kvart i',
    subject: 'matte',
    youtube: 'r85kolIjBLY' },
  { key: 'kvart_över',
    name: 'kvart över',
    subject: 'matte',
    youtube: 'TOMzkZl9h80' },
  { key: 'kvot',
    name: 'kvot',
    subject: 'matte',
    youtube: '4ii-ApbLoQI' },
  { key: 'läge',
    name: 'läge',
    subject: 'matte',
    youtube: 'pCl5RNSfnhY' },
  { key: 'längd',
    name: 'längd',
    subject: 'matte',
    youtube: 'PT_Ax2IMi-o' },
  { key: 'längre_alt_1',
    name: 'längre alt 1',
    subject: 'matte',
    youtube: 'xAxff9CG48A' },
  { key: 'längre_alt_2',
    name: 'längre alt 2',
    subject: 'matte',
    youtube: 'coH0a43Ga8Y' },
  { key: 'längst_alt_1',
    name: 'längst alt 1',
    subject: 'matte',
    youtube: 'Zq4HnLI77ig' },
  { key: 'längst_alt_2',
    name: 'längst alt 2',
    subject: 'matte',
    youtube: 'hWMQetFohds' },
  { key: 'längst_till_höger',
    name: 'längst till höger',
    subject: 'matte',
    youtube: 'ZLF2sM2yj7I' },
  { key: 'längst_till_vänster',
    name: 'längst till vänster',
    subject: 'matte',
    youtube: 'OhJpB0Y7ZW8' },
  { key: 'lätt',
    name: 'lätt',
    subject: 'matte',
    youtube: 'QUjIzKAbo3E' },
  { key: 'lätt_tung',
    name: 'lätt tung',
    subject: 'matte',
    youtube: 'xEdEW8bcOkI' },
  { key: 'lång_alt_1',
    name: 'lång alt 1',
    subject: 'matte',
    youtube: 'dt7xPBISAa8' },
  { key: 'lång_alt_2',
    name: 'lång alt 2',
    subject: 'matte',
    youtube: 'qDOszZ-II2E' },
  { key: 'lång_kort_alt_1',
    name: 'lång kort alt 1',
    subject: 'matte',
    youtube: 'ooQo8RETSiA' },
  { key: 'lång_kort_alt_2',
    name: 'lång kort alt 2',
    subject: 'matte',
    youtube: 'VHuwcubqQz0' },
  { key: 'lång_längre_längst_alt_2',
    name: 'lång längre längst alt 2',
    subject: 'matte',
    youtube: 'GloiXyN8Ad0' },
  { key: 'lång_långre_längst_alt_1',
    name: 'lång långre längst alt 1',
    subject: 'matte',
    youtube: 'r9ZpnGb0uY4' },
  { key: 'lika',
    name: 'lika',
    subject: 'matte',
    youtube: 'mIgrqzcl-WQ' },
  { key: 'lika_många',
    name: 'lika många',
    subject: 'matte',
    youtube: 'H_02pMwdAE4' },
  { key: 'likhet',
    name: 'likhet',
    subject: 'matte',
    youtube: 'kAnCYqhx7ro' },
  { key: 'likhetstecken',
    name: 'likhetstecken',
    subject: 'matte',
    youtube: '3rXntc9_R68' },
  { key: 'linjal',
    name: 'linjal',
    subject: 'matte',
    youtube: 'AP0mFLMvPCk' },
  { key: 'linje',
    name: 'linje',
    subject: 'matte',
    youtube: '_mBYtFPDsOE' },
  { key: 'linjediagram',
    name: 'linjediagram',
    subject: 'matte',
    youtube: 'MBsOcoYla2k' },
  { key: 'liter',
    name: 'liter',
    subject: 'matte',
    youtube: 'cwdECJPAwV8' },
  { key: 'lösa_problem',
    name: 'lösa problem',
    subject: 'matte',
    youtube: 'yMQdNq1gxXw' },
  { key: 'lösning',
    name: 'lösning',
    subject: 'matte',
    youtube: 'Tw7I9D5No6I' },
  { key: 'm', name: 'm', subject: 'matte', youtube: 'Kmfws0j_-i8' },
  { key: 'massa',
    name: 'massa',
    subject: 'matte',
    youtube: 'nkgwY9wKODQ' },
  { key: 'matte',
    name: 'matte',
    subject: 'matte',
    youtube: '6VNzbU7OXgo' },
  { key: 'mattespråk',
    name: 'mattespråk',
    subject: 'matte',
    youtube: 'MyWkS00ncYA' },
  { key: 'mäta',
    name: 'mäta',
    subject: 'matte',
    youtube: 'B4yK-NbJutg' },
  { key: 'många',
    name: 'många',
    subject: 'matte',
    youtube: 'tapj900069Q' },
  { key: 'många_få',
    name: 'många få',
    subject: 'matte',
    youtube: 'AQ7VXgc6usE' },
  { key: 'månghörning',
    name: 'månghörning',
    subject: 'matte',
    youtube: 'xLdMMB1TuXI' },
  { key: 'måttenhet',
    name: 'måttenhet',
    subject: 'matte',
    youtube: 'seWIhJ5GcTo' },
  { key: 'mellan',
    name: 'mellan',
    subject: 'matte',
    youtube: 'TLSuwOtwpp0' },
  { key: 'milliliter',
    name: 'milliliter',
    subject: 'matte',
    youtube: 'b5AqZzc6hwY' },
  { key: 'miniräknare',
    name: 'miniräknare',
    subject: 'matte',
    youtube: 'Dje_m5wznjQ' },
  { key: 'minskning',
    name: 'minskning',
    subject: 'matte',
    youtube: 'eZWEfOb8TDE' },
  { key: 'minut',
    name: 'minut',
    subject: 'matte',
    youtube: 'IXG0eHg3Hb4' },
  { key: 'mitten',
    name: 'mitten',
    subject: 'matte',
    youtube: '2Ehsksi40zs' },
  { key: 'mm',
    name: 'mm',
    subject: 'matte',
    youtube: 'uoo7T_im66Y' },
  { key: 'mönster',
    name: 'mönster',
    subject: 'matte',
    youtube: '9gIZvLw5_0s' },
  { key: 'mönsterdelar',
    name: 'mönsterdelar',
    subject: 'matte',
    youtube: 'G0gtfFXXgVM' },
  { key: 'multipicera',
    name: 'multipicera',
    subject: 'matte',
    youtube: '-3qqTWDo7Dc' },
  { key: 'multiplikation',
    name: 'multiplikation',
    subject: 'matte',
    youtube: 'UIuMGFyoohM' },
  { key: 'multiplikation_faktor*faktor=produkt',
    name: 'multiplikation faktor*faktor=produkt',
    subject: 'matte',
    youtube: 'U-2Tljfuh0w' },
  { key: 'multiplikationstabell',
    name: 'multiplikationstabell',
    subject: 'matte',
    youtube: 'U8u3lBraYH0' },
  { key: 'naturiga_tal',
    name: 'naturiga tal',
    subject: 'matte',
    youtube: 'GV7vKeP_vjw' },
  { key: 'nämnare',
    name: 'nämnare',
    subject: 'matte',
    youtube: '4vsgulZyeuk' },
  { key: 'negativa_tal',
    name: 'negativa tal',
    subject: 'matte',
    youtube: '8EyyKADLRHM' },
  { key: 'nere',
    name: 'nere',
    subject: 'matte',
    youtube: 'Jkb9hm0PBLg' },
  { key: 'nionde',
    name: 'nionde',
    subject: 'matte',
    youtube: '7xupHESqBmc' },
  { key: 'nummer',
    name: 'nummer',
    subject: 'matte',
    youtube: 'yKdqVq8B9d4' },
  { key: 'nummerordning',
    name: 'nummerordning',
    subject: 'matte',
    youtube: 'hqZFGhBAnZ0' },
  { key: 'objekt',
    name: 'objekt',
    subject: 'matte',
    youtube: 'FZTpw6intio' },
  { key: 'olika',
    name: 'olika',
    subject: 'matte',
    youtube: 'KgeoBGeq_sg' },
  { key: 'omkrets',
    name: 'omkrets',
    subject: 'matte',
    youtube: 'R1rs1t62NuU' },
  { key: 'område',
    name: 'område',
    subject: 'matte',
    youtube: 'JbJ7Trtlwg4' },
  { key: 'ordning',
    name: 'ordning',
    subject: 'matte',
    youtube: 'aA4swfhmEss' },
  { key: 'ordningstal',
    name: 'ordningstal',
    subject: 'matte',
    youtube: 'p6GRwR3Ih0c' },
  { key: 'ökning',
    name: 'ökning',
    subject: 'matte',
    youtube: 'atx6l5GU-po' },
  { key: 'överslagsräkning',
    name: 'överslagsräkning',
    subject: 'matte',
    youtube: '4zrn3NgW9kU' },
  { key: 'par',
    name: 'par',
    subject: 'matte',
    youtube: '6d6tWzSY0YU' },
  { key: 'parallella',
    name: 'parallella',
    subject: 'matte',
    youtube: 'eZVDtljNFiQ' },
  { key: 'prick',
    name: 'prick',
    subject: 'matte',
    youtube: 'IpuymCgjnjA' },
  { key: 'prickar',
    name: 'prickar',
    subject: 'matte',
    youtube: '1SDh45DU_BM' },
  { key: 'prisma',
    name: 'prisma',
    subject: 'matte',
    youtube: 'QPEDV0eGI0Q' },
  { key: 'problemlösning',
    name: 'problemlösning',
    subject: 'matte',
    youtube: '63INJFROIcY' },
  { key: 'produkt',
    name: 'produkt',
    subject: 'matte',
    youtube: 'EArQ-iuBKqY' },
  { key: 'punkt',
    name: 'punkt',
    subject: 'matte',
    youtube: '7r7EAMofus0' },
  { key: 'pyramid',
    name: 'pyramid',
    subject: 'matte',
    youtube: 'YmvtSrQa3Q8' },
  { key: 'rad',
    name: 'rad',
    subject: 'matte',
    youtube: '6vCqJY4gwzc' },
  { key: 'rak',
    name: 'rak',
    subject: 'matte',
    youtube: 'WsHGdXix_VY' },
  { key: 'räkna',
    name: 'räkna',
    subject: 'matte',
    youtube: 'yqHMKsaIkpg' },
  { key: 'räknehändelse',
    name: 'räknehändelse',
    subject: 'matte',
    youtube: 'phYvZd6ypdc' },
  { key: 'räknesätt',
    name: 'räknesätt',
    subject: 'matte',
    youtube: 'GRQlfvgsVPY' },
  { key: 'rätblock',
    name: 'rätblock',
    subject: 'matte',
    youtube: '6T-WfoXvnSY' },
  { key: 'rätvinkel',
    name: 'rätvinkel',
    subject: 'matte',
    youtube: 'qku9HjMDcaQ' },
  { key: 'redovisa',
    name: 'redovisa',
    subject: 'matte',
    youtube: 'oCUGz2M241Q' },
  { key: 'rektangel',
    name: 'rektangel',
    subject: 'matte',
    youtube: 'zkC86kFfEyI' },
  { key: 'resten',
    name: 'resten',
    subject: 'matte',
    youtube: '0JC3lIAWJ2w' },
  { key: 'resultat',
    name: 'resultat',
    subject: 'matte',
    youtube: 'jyn2EYpCJrk' },
  { key: 'riktning',
    name: 'riktning',
    subject: 'matte',
    youtube: '34-FOECpXEI' },
  { key: 'rimlighet',
    name: 'rimlighet',
    subject: 'matte',
    youtube: 'd_WyJkCQKSM' },
  { key: 'ruta',
    name: 'ruta',
    subject: 'matte',
    youtube: 'yFHkETEEHEw' },
  { key: 'samband',
    name: 'samband',
    subject: 'matte',
    youtube: 'OAjX2aErHRU' },
  { key: 'samma',
    name: 'samma',
    subject: 'matte',
    youtube: 'SqynQUEjRMc' },
  { key: 'sammanläggning',
    name: 'sammanläggning',
    subject: 'matte',
    youtube: '6A6oogPqpuE' },
  { key: 'samtala',
    name: 'samtala',
    subject: 'matte',
    youtube: 'RqZVW08Gb5I' },
  { key: 'sannolikhet',
    name: 'sannolikhet',
    subject: 'matte',
    youtube: 'KqfkzbS466Y' },
  { key: 'sämre',
    name: 'sämre',
    subject: 'matte',
    youtube: 'xRJce6KPx94' },
  { key: 'sämst',
    name: 'sämst',
    subject: 'matte',
    youtube: 'KwRlF3b_Syc' },
  { key: 'sekund',
    name: 'sekund',
    subject: 'matte',
    youtube: '9Hv_GrBNDtU' },
  { key: 'sida',
    name: 'sida',
    subject: 'matte',
    youtube: 'BDM8nW3Fp-s' },
  { key: 'siffra',
    name: 'siffra',
    subject: 'matte',
    youtube: '7ewlr3oC-30' },
  { key: 'sist',
    name: 'sist',
    subject: 'matte',
    youtube: 'GbqY-VD3lVU' },
  { key: 'sjätte',
    name: 'sjätte',
    subject: 'matte',
    youtube: 'kNuqNIYdxqY' },
  { key: 'sjunde',
    name: 'sjunde',
    subject: 'matte',
    youtube: 'JdhoUONX-k4' },
  { key: 'skala',
    name: 'skala',
    subject: 'matte',
    youtube: 'MvgDBUrEo8o' },
  { key: 'skillnad',
    name: 'skillnad',
    subject: 'matte',
    youtube: '44f2cmx0Xl0' },
  { key: 'skillt_från',
    name: 'skillt från',
    subject: 'matte',
    youtube: 'sQ0jz1FyXHI' },
  { key: 'sortera',
    name: 'sortera',
    subject: 'matte',
    youtube: 'TY7A6Hcr9OQ' },
  { key: 'spetsig_vinkel',
    name: 'spetsig vinkel',
    subject: 'matte',
    youtube: 'wv1QOEwsIBc' },
  { key: 'stapel',
    name: 'stapel',
    subject: 'matte',
    youtube: 'OUQrK5wVSF4' },
  { key: 'stapeldiagram',
    name: 'stapeldiagram',
    subject: 'matte',
    youtube: 'Z5zc-jnLXAw' },
  { key: 'statestik',
    name: 'statestik',
    subject: 'matte',
    youtube: '98aeHFuTyMM' },
  { key: 'stor_alt_1',
    name: 'stor alt 1',
    subject: 'matte',
    youtube: 'V9-A7OARysA' },
  { key: 'stor_alt_2',
    name: 'stor alt 2',
    subject: 'matte',
    youtube: 'DFaGHI4i22U' },
  { key: 'stor_liten_alt_1',
    name: 'stor liten alt 1',
    subject: 'matte',
    youtube: 'p_-HnFKqZag' },
  { key: 'stor_liten_alt_2',
    name: 'stor liten alt 2',
    subject: 'matte',
    youtube: 'RoeoG_OWets' },
  { key: 'stor_större_störst_alt_1',
    name: 'stor större störst alt 1',
    subject: 'matte',
    youtube: 'OhrQmlwUKfw' },
  { key: 'stor_större_störst_alt_2',
    name: 'stor större störst alt 2',
    subject: 'matte',
    youtube: 'a_uvDc-DTv8' },
  { key: 'storlek',
    name: 'storlek',
    subject: 'matte',
    youtube: 'qbAEBS-M83s' },
  { key: 'storleksordning',
    name: 'storleksordning',
    subject: 'matte',
    youtube: '83hp0bhTLBo' },
  { key: 'större_alt_1',
    name: 'större alt 1',
    subject: 'matte',
    youtube: 'W-QZrKyLzMk' },
  { key: 'större_alt_2',
    name: 'större alt 2',
    subject: 'matte',
    youtube: 'bI9CA1322Rg' },
  { key: 'störst_alt_1',
    name: 'störst alt 1',
    subject: 'matte',
    youtube: 'zIeRjJC_vQk' },
  { key: 'störst_alt_2',
    name: 'störst alt 2',
    subject: 'matte',
    youtube: 'uW_BA3GoSmk' },
  { key: 'strategi',
    name: 'strategi',
    subject: 'matte',
    youtube: 'lCOOZkooMvk' },
  { key: 'sträcka',
    name: 'sträcka',
    subject: 'matte',
    youtube: 'yukUGU-fYtg' },
  { key: 'streck',
    name: 'streck',
    subject: 'matte',
    youtube: '5eizcvoOtnE' },
  { key: 'subtration',
    name: 'subtration',
    subject: 'matte',
    youtube: 'MMTg3OV5xdE' },
  { key: 'subtration_term_term=differens',
    name: 'subtration term term=differens',
    subject: 'matte',
    youtube: 'ScDEGbpOn0E' },
  { key: 'summa',
    name: 'summa',
    subject: 'matte',
    youtube: 'IRRBtpOW8_M' },
  { key: 'svar',
    name: 'svar',
    subject: 'matte',
    youtube: 't6HZEJT81IE' },
  { key: 'sydoyta',
    name: 'sydoyta',
    subject: 'matte',
    youtube: 'VaN11Q5zmG0' },
  { key: 'symbol',
    name: 'symbol',
    subject: 'matte',
    youtube: 'eVsO1pwR_CM' },
  { key: 'symmetri',
    name: 'symmetri',
    subject: 'matte',
    youtube: 'aQ2Cki0sucE' },
  { key: 'symmetrisk',
    name: 'symmetrisk',
    subject: 'matte',
    youtube: 'w3XX_UWChuo' },
  { key: 'system',
    name: 'system',
    subject: 'matte',
    youtube: '3Kv3pw2SYpQ' },
  { key: 'tabell',
    name: 'tabell',
    subject: 'matte',
    youtube: 'H-nI-NYfLtw' },
  { key: 'tal',
    name: 'tal',
    subject: 'matte',
    youtube: 'gudVtoM0f-4' },
  { key: 'talblock',
    name: 'talblock',
    subject: 'matte',
    youtube: 'wpuSnzK7y-U' },
  { key: 'talfamilj',
    name: 'talfamilj',
    subject: 'matte',
    youtube: 'FmdEnYW47D4' },
  { key: 'talföljd',
    name: 'talföljd',
    subject: 'matte',
    youtube: 'txiJuNvH9qU' },
  { key: 'talgåta',
    name: 'talgåta',
    subject: 'matte',
    youtube: 'WJoKn2pXoPM' },
  { key: 'talkamrat',
    name: 'talkamrat',
    subject: 'matte',
    youtube: 'pXOubg-MU5E' },
  { key: 'talkompis',
    name: 'talkompis',
    subject: 'matte',
    youtube: 'uH79ydCHATk' },
  { key: 'tallinje',
    name: 'tallinje',
    subject: 'matte',
    youtube: 'v3IqwXEj9AE' },
  { key: 'talmönster',
    name: 'talmönster',
    subject: 'matte',
    youtube: '9A6hRcwpu7E' },
  { key: 'talområde',
    name: 'talområde',
    subject: 'matte',
    youtube: 'JiQRrtAgsJo' },
  { key: 'talrad',
    name: 'talrad',
    subject: 'matte',
    youtube: 'fUMOiZXTL7c' },
  { key: 'talsort',
    name: 'talsort',
    subject: 'matte',
    youtube: 'EhiLsYmVE-Q' },
  { key: 'talsystem',
    name: 'talsystem',
    subject: 'matte',
    youtube: 'tZIxn2RTFJQ' },
  { key: 'täljare',
    name: 'täljare',
    subject: 'matte',
    youtube: 'JN1C10pjCFM' },
  { key: 'term',
    name: 'term',
    subject: 'matte',
    youtube: '6cWFWzfxyzE' },
  { key: 'tidsdifferens',
    name: 'tidsdifferens',
    subject: 'matte',
    youtube: 'Qbp6kEBOTpg' },
  { key: 'tillbaka',
    name: 'tillbaka',
    subject: 'matte',
    youtube: 'x9IMcq26lv8' },
  { key: 'timme',
    name: 'timme',
    subject: 'matte',
    youtube: 'SpnGQrsujbw' },
  { key: 'tionde',
    name: 'tionde',
    subject: 'matte',
    youtube: 'qha7wDZMZP0' },
  { key: 'tiotal',
    name: 'tiotal',
    subject: 'matte',
    youtube: '2NCFgWZe7dA' },
  { key: 'tjock_smal',
    name: 'tjock smal',
    subject: 'matte',
    youtube: 'oWwuiwQwMs0' },
  { key: 'tolfte',
    name: 'tolfte',
    subject: 'matte',
    youtube: '5ss1YProXV0' },
  { key: 'tredje',
    name: 'tredje',
    subject: 'matte',
    youtube: '1Xyt8Kf8jUY' },
  { key: 'tredjedel',
    name: 'tredjedel',
    subject: 'matte',
    youtube: 'rmatv3QAe0k' },
  { key: 'trehörning',
    name: 'trehörning',
    subject: 'matte',
    youtube: 'VHzGMrD_Njw' },
  { key: 'tresiffrigt',
    name: 'tresiffrigt',
    subject: 'matte',
    youtube: 'VBZggTHurOU' },
  { key: 'triangel',
    name: 'triangel',
    subject: 'matte',
    youtube: 'EGC5Z_xhvP0' },
  { key: 'trubbig_vinkel_alt_1',
    name: 'trubbig vinkel alt 1',
    subject: 'matte',
    youtube: 'j5CZxnA4Yzs' },
  { key: 'trubbig_vinkel_alt_2',
    name: 'trubbig vinkel alt 2',
    subject: 'matte',
    youtube: '3UnwM0WKOnI' },
  { key: 'tung',
    name: 'tung',
    subject: 'matte',
    youtube: 'dzT6xtg-Nns' },
  { key: 'tung_tyngre_tyngst',
    name: 'tung tyngre tyngst',
    subject: 'matte',
    youtube: 'M1UFsVhvM1I' },
  { key: 'två_dimentionella_figurer',
    name: 'två dimentionella figurer',
    subject: 'matte',
    youtube: 'WgdxEhNDbbY' },
  { key: 'tvåsiffrigt',
    name: 'tvåsiffrigt',
    subject: 'matte',
    youtube: 'ZnKoABi58b0' },
  { key: 'tyngre',
    name: 'tyngre',
    subject: 'matte',
    youtube: 'wqfYD3xqsGE' },
  { key: 'tyngst',
    name: 'tyngst',
    subject: 'matte',
    youtube: 'UtVC2TuFSTk' } ];

  var Root = Backbone.View.extend({
    template: document.getElementById('view-root').innerText,
    render: function() {
      this.$el = $(this.template);
/*
      var stage = new createjs.Stage(this.$el.filter('canvas').get(0));

      var building = new createjs.Rectangle(0, 0, 400, 250);
      building.graphics.beginFill("#9f2929");
      stage.addChild(building);

      var door = new createjs.Shape();
      door.graphics.beginFill("#441817").rect(building.w / 2 - 60, building.h - 150, 120, 150);
      stage.addChild(door);

      stage.update();
*/
      return this;
    }
  });

  var School = Backbone.View.extend({
    template: _.template(document.getElementById('view-school').innerText),
    initialize: function() {
      this.$el = $(this.template({ subjects: subjects }));
    },
    render: function () {
      return this;
    }
  });

  var Subject = Backbone.View.extend({
    template: _.template(document.getElementById('view-subject').innerText),
    initialize: function (s) {
      var view = this;
      var items = _.filter(words, function(w) { return w.subject === s; });

      view.$el = $(this.template({ words: items }));
      view.$modal = this.$el.filter('#video-modal');
      view.$iframe = this.$modal.find('iframe');

      view.$el.on('click', '.link', function(e) {
        var width = $(document.body).width(),
          aspectRatio = view.$iframe.height() / view.$iframe.width()

          if (width > 600) {
            width = 600;
          }

        view.$iframe.get(0).contentWindow.location.replace('http://www.youtube.com/embed/' + $(this).data('youtube') + '?rel=0');
        view.$iframe.attr('height', width * aspectRatio);
        view.$iframe.attr('width', width);
      });
      view.$modal.on('show.bs.modal', function () {
      });

      view.$modal.on('hide.bs.modal', function () {
        view.$iframe.get(0).contentWindow.location.replace('');
      });

    }
  });

  var Router = Backbone.Router.extend({
    routes: {
      '': 'root',
      'school': 'school',
      'school/:subject': 'subject'
    },
    initialize: function() {
      Backbone.history.start();
      return this;
    },
    root: function() {
      this.setView(new Root());
      return this;
    },
    school: function () {
      this.setView(new School());
      return this;
    },
    subject: function (subject) {
      this.setView(new Subject(subject));
      return this;
    },
    setView: function(view) {
      if (this.view) {
        this.view.remove();
      }
      this.view = view;

      $('#app').append(this.view.render().$el);
    }
  });

  window.app = new Router();
}());
